version: "3.3"
services:
  db:
    image: postgres:13
    volumes:
      - app-db-data:/var/lib/postgresql/data/pgdata
      - ./init-app-db.sh:/docker-entrypoint-initdb.d/init-app-db.sh
    env_file:
      - .env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    networks:
      - default
    depends_on:
      - db
    env_file:
      - .env
  
  server:
    depends_on:
      - db
    env_file:
      - .env
    build:
      context: .
    ports:
      - "8080:80"
  
volumes:
  app-db-data: